### ISSUE TITLE
Create a flamegraph from callgrind output

### ISSUE THREAD

**Issue by Joining7943** [Joining7943/iai-callgrind#23]
`kcachegrind` is a good visualizer of callgrind output but it visualizes call chains by using nested squares. A `flamegraph` as produced for example by the `inferno` crate is a more common way to visualize profiled code. So, a flamegraph would be a great addition and it's also a great way to visualize the difference between `*.out.old` callgrind output and new `*.out`.

**Comment by gamma0987** [comment]
Currently, the main purposes of callgrind flamegraphs are to get a *quick* overview over the inclusive costs of each function and to see in differential flamegraphs where the highest cost increases/decreases are. Although this feature is still very basic, the interpretation logic of the callgrind data looks ok to me. Mainly, the usage of the term flamegraph originates in the usage of inferno, a flamegraph generator, as backend for the callgrind flamegraphs.

First of all, these aren't conventional flamegraphs because there isn't the usual real time information in the callgrind/cachegrind output and no actual before and after a function which renders the construction of code-paths as usual impossible. However, what can be shown is the total amount of instructions (or whatever callgrind metric you're interested in) of each function. Again, this serves the purpose to get a *quick* overview over the inclusive costs of each function as bar width. What I understand as inclusive costs are the costs of all instructions in the function itself plus the costs of each called function. I hope this helps interpreting the callgrind flamegraph output.

For example a program like this: main with self costs of 20 Instructions calls func1 and then func2. func1 calls func1_sub1. The numbers in parentheses are the self costs.

```
main (20 Ir) -> func1 (30 Ir) -> func1_sub1 (50 Ir)
             -> func2 (90 Ir)
```

results in a callgrind flamegraph:

```
main  // 190 Ir
func2 // 90 Ir
func1 // 80 Ir
func1_sub_1 // 50 Ir
```

If you want to analyze further than that, I highly recommend kcachegrind which offers a far deeper view on the callgrind/cachegrind data. In the future I'd like to integrate the self costs of each function in the bar in a different color which could improve the quick identification of functions which have a good potential for optimizations.
